### ISSUE TITLE
play/paused doesn't update

### ISSUE THREAD

**Issue by borgswen** [nagyrobi/home-assistant-custom-components-linkplay#17]
hi, I am using an audiocast m5 and I just installed yout integration, thank you so much btw.
But the play/pause button isn't working in homeassistant. when music is playing and i press it, the music stops but the button doesn't update, also when I press it again the music doesn't start playing and the history tab in home assistant show that the state still shows playing. When I used my browser to go to the httpapi, the state did show right.

**Comment by nagyrobi** [comment]
What music source do you play, and what card do you use to display in Lovelace?

**Comment by borgswen** [comment]
I am using the standard Lovelace card and i have tried the mini media player card, but it didn't make a difference. I am listening to music through Spotify, but I have tried TuneIn, and that didn't work either.

**Comment by nagyrobi** [comment]
Well this is more or less intended to control playback of contents initiated through HA.

It's a weirdness of Lovelace, as it tries to combine pause and stop functionality in the same button. For min-media-plyer it [can be overridden](https://github.com/kalkih/mini-media-player#hide-object) in Lovelace config:
```
    hide:
      play_pause: true
      play_stop: false
```

**Comment by borgswen** [comment]
Aha, hmmm what I was trying to accomplish is that my stereo amplifier turns on when I start using the audiocast device, but as the state doesn't update I think I'll have to find an other way. Thanks tho.

**Comment by nagyrobi** [comment]
Well what I have for that is
```
- alias: 'Amp on'
  trigger:
    platform: template
    value_template: "{% if is_state('media_player.room1', 'playing') %}True{% endif %}"
  action:
    - service: switch.turn_on
      entity_id: switch.amp
```
