### ISSUE TITLE
Turn on not always detected by automation

### ISSUE THREAD

**Issue by qistoph** [nagyrobi/home-assistant-custom-components-linkplay#45]
My linkplay speaker is not always powered. When it's powered on I'd like it to start playing a radio station. The automation I use is detailed below and is based on detecting a status change from `unavailable` to `idle`.

This is however not always detected and sometimes quite delayed.

Is there anything you could do to help me figure out the issue here?
Anything I can do/check for additional information?

```
alias: Badkamer Qmusic
description: ''
trigger:
  - platform: state
    entity_id: media_player.badkamer_muziek
    from: unavailable
    to: idle
condition: []
action:
  - service: media_player.select_source
    target:
      entity_id: media_player.badkamer_muziek
    data:
      source: Qmusic
mode: single
```
